package view;

import javax.swing.ImageIcon;
import model.Banco;
import model.Jogador;

public class TelaJogo extends javax.swing.JFrame {
    TelaVenceu winner = new TelaVenceu();
    TelaPerdeu loser = new TelaPerdeu();
    Banco bank = new Banco();
    Jogador player;
    int erros = 0;
    String letra = " ";
    String palavra = bank.sorteio();
    char palavraSecreta[] = new char[palavra.length()];

    public TelaJogo() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logo_icon.png")).getImage());
        fail1.setVisible(false);
        fail2.setVisible(false);
        fail3.setVisible(false);
        fail4.setVisible(false);
        fail5.setVisible(false);
        
    }

    public void passarJogador(Jogador player) {
        this.player = player;
        tfNomeJogador.setText(player.getNome());
        inicializarPalavraSecreta(palavraSecreta);//Aproveito para inicializar a palavra
        jogar(letra);
    }

    public void jogar(String letra) {

        tfQntLetras.setText("A palavra tem " + palavra.length() + " letras.");

        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));

        boolean contemLetra = palavra.contains(letra);

        if (contemLetra) {
            for (int i = 0; i < palavra.length(); i++) {

                if (palavra.charAt(i) == letra.charAt(0)) {
                    palavraSecreta[i] = letra.charAt(0);
                }
            }
        } else {
            erros++;
        }
        mostrarCondenado(erros);
        
       
            if (erros > 4) {
                loser.setVisible(true);
                dispose();
            }else if(verificarVitoria(palavra, palavraSecreta)){
                winner.setVisible(true);
                dispose();
            }
        

    }

    public String imprimirPalavraSecreta(char[] palavraSecreta) {
        String tracinho = "";
        for (int i = 0; i < palavraSecreta.length; i++) {
            tracinho += palavraSecreta[i] + " ";
        }
        return tracinho;
    }

    public char[] inicializarPalavraSecreta(char[] palavraSecreta) {
        for (int i = 0; i < palavraSecreta.length; i++) {
            palavraSecreta[i] = '_';
        }
        return palavraSecreta;
    }

    public boolean verificarVitoria(String palavraSorteada, char[] palavraSecreta) {
        String palavraEscondidaAuxiliar = new String(palavraSecreta);
        if (palavraSorteada.equals(palavraEscondidaAuxiliar)) {
            return true;
        }

        return false;
    }

    public void mostrarCondenado(int qntErros) {
        switch (qntErros) {
            case 1:
                fail0.setVisible(true);
                break;
            case 2:
                fail1.setVisible(true);
                break;
            case 3:
                fail2.setVisible(true);
                fail3.setVisible(true);
                break;
            case 4:
                fail4.setVisible(true);
                break;
            case 5:
                fail5.setVisible(true);
                break;
            default:
                fail0.setVisible(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNomeJogador = new javax.swing.JLabel();
        fail0 = new javax.swing.JLabel();
        fail1 = new javax.swing.JLabel();
        fail2 = new javax.swing.JLabel();
        fail3 = new javax.swing.JLabel();
        fail4 = new javax.swing.JLabel();
        fail5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfQntLetras = new javax.swing.JLabel();
        tfPalavra = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Forca");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNomeJogador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(tfNomeJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 260, 40));

        fail0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e0.png"))); // NOI18N
        getContentPane().add(fail0, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 39, -1, -1));

        fail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e1.png"))); // NOI18N
        getContentPane().add(fail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 39, -1, -1));

        fail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e2.png"))); // NOI18N
        getContentPane().add(fail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 39, -1, -1));

        fail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e3.png"))); // NOI18N
        getContentPane().add(fail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 39, -1, -1));

        fail4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e4.png"))); // NOI18N
        getContentPane().add(fail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 39, -1, -1));

        fail5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e5.png"))); // NOI18N
        getContentPane().add(fail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 39, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Jogador(a):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 40));

        tfQntLetras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfQntLetras.setText("Dica: tem 0 letras.");
        getContentPane().add(tfQntLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 210, 40));

        tfPalavra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tfPalavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfPalavra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tfPalavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 360, 40));

        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraA.png"))); // NOI18N
        btnA.setToolTipText("");
        btnA.setPreferredSize(new java.awt.Dimension(30, 30));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        getContentPane().add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 30, 30));

        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraD.png"))); // NOI18N
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        getContentPane().add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 30, 30));

        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraB.png"))); // NOI18N
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        getContentPane().add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 30, 30));

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraC.png"))); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 30, 30));

        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraE.png"))); // NOI18N
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        getContentPane().add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 30, 30));

        btnK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraK.png"))); // NOI18N
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });
        getContentPane().add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 30, 30));

        btnF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraF.png"))); // NOI18N
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        getContentPane().add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 30, 30));

        btnG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraG.png"))); // NOI18N
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 30, 30));

        btnH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraH.png"))); // NOI18N
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });
        getContentPane().add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 30, 30));

        btnI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraI.png"))); // NOI18N
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });
        getContentPane().add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 30, 30));

        btnL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraL.png"))); // NOI18N
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });
        getContentPane().add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 30, 30));

        btnM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraM.png"))); // NOI18N
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });
        getContentPane().add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 30, 30));

        btnN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraN.png"))); // NOI18N
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });
        getContentPane().add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 30, 30));

        btnJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraJ.png"))); // NOI18N
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 30, 30));

        btnO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraO.png"))); // NOI18N
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });
        getContentPane().add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 30, 30));

        btnP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraP.png"))); // NOI18N
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        getContentPane().add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 30, 30));

        btnQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraQ.png"))); // NOI18N
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 30, 30));

        btnR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraR.png"))); // NOI18N
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });
        getContentPane().add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 30, 30));

        btnS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraS.png"))); // NOI18N
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });
        getContentPane().add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 30, 30));

        btnU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraU.png"))); // NOI18N
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });
        getContentPane().add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 30, 30));

        btnV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraV.png"))); // NOI18N
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });
        getContentPane().add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 30, 30));

        btnW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraW.png"))); // NOI18N
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });
        getContentPane().add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 30, 30));

        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraX.png"))); // NOI18N
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });
        getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 30, 30));

        btnZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraZ.png"))); // NOI18N
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });
        getContentPane().add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 30, 30));

        btnY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraY.png"))); // NOI18N
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });
        getContentPane().add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 30, 30));

        btnT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraT.png"))); // NOI18N
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });
        getContentPane().add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 30, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_jogo.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        btnA.setVisible(false);
        letra = "a";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        btnB.setVisible(false);
        letra = "b";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        btnC.setVisible(false);
        letra = "c";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        btnD.setVisible(false);
        letra = "d";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        btnE.setVisible(false);
        letra = "e";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        btnF.setVisible(false);
        letra = "f";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnFActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        btnG.setVisible(false);
        letra = "g";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnGActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        btnH.setVisible(false);
        letra = "h";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnHActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        btnI.setVisible(false);
        letra = "i";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnIActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        btnJ.setVisible(false);
        letra = "j";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        btnK.setVisible(false);
        letra = "k";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnKActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        btnL.setVisible(false);
        letra = "l";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnLActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        btnM.setVisible(false);
        letra = "m";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnMActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        btnN.setVisible(false);
        letra = "n";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnNActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        btnO.setVisible(false);
        letra = "o";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        btnP.setVisible(false);
        letra = "p";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnPActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        btnQ.setVisible(false);
        letra = "q";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnQActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        btnR.setVisible(false);
        letra = "r";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnRActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        btnS.setVisible(false);
        letra = "s";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnSActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        btnT.setVisible(false);
        letra = "t";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnTActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        btnU.setVisible(false);
        letra = "u";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnUActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        btnV.setVisible(false);
        letra = "v";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnVActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        btnW.setVisible(false);
        letra = "w";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnWActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        btnX.setVisible(false);
        letra = "x";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnXActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        btnY.setVisible(false);
        letra = "y";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnYActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        btnZ.setVisible(false);
        letra = "z";
        jogar(letra);
        tfPalavra.setText(imprimirPalavraSecreta(palavraSecreta));
    }//GEN-LAST:event_btnZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JLabel fail0;
    private javax.swing.JLabel fail1;
    private javax.swing.JLabel fail2;
    private javax.swing.JLabel fail3;
    private javax.swing.JLabel fail4;
    private javax.swing.JLabel fail5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tfNomeJogador;
    private javax.swing.JLabel tfPalavra;
    private javax.swing.JLabel tfQntLetras;
    // End of variables declaration//GEN-END:variables
}
